import type { CognitionSlide, DeckSection } from '../types/cognition';

export const sectionRail = [
  { section: 'recognition', label: 'Recognition' },
  { section: 'mismatch', label: 'Mismatch' },
  { section: 'translation', label: 'Translation' },
  { section: 'invitation', label: 'Invitation' },
] as const satisfies ReadonlyArray<{ section: DeckSection; label: string }>;

export const sectionLabels: Record<DeckSection, string> = Object.fromEntries(
  sectionRail.map(({ section, label }) => [section, label]),
) as Record<DeckSection, string>;

export const cognitionSlides: CognitionSlide[] = [
  {
    id: 'recognition-01',
    section: 'recognition',
    visualState: 'signal',
    eyebrow: 'Act I · Recognition',
    title: 'Cognition Requires Infrastructure',
    body: 'If serious thinking matters, the environment must carry orientation, memory, and continuity instead of demanding that every person rebuild them alone.',
    kicker: 'Act I · Cover',
  },
  {
    id: 'recognition-02',
    section: 'recognition',
    visualState: 'signal',
    eyebrow: 'Act I · Recognition',
    title: 'This is not a discipline problem.',
    body: 'Configuration shapes cognition. When tools, rituals, and defaults make context fragile, even capable people will look inconsistent inside the system.',
    kicker: 'Act I · Configuration',
  },
  {
    id: 'recognition-03',
    section: 'recognition',
    visualState: 'throughput',
    eyebrow: 'Act I · Recognition',
    title: 'Throughput is now a cognitive constraint.',
    body: 'The modern bottleneck is not just execution speed. It is how much state a person can carry while switching between decisions, tools, and timelines.',
    kicker: 'Act I · Throughput',
  },
  {
    id: 'recognition-04',
    section: 'recognition',
    visualState: 'signal',
    eyebrow: 'Act I · Recognition',
    title: 'We shape our tools and thereafter our tools shape us.',
    body: 'Recognition starts here: our systems are not neutral containers. They actively train what a team can notice, preserve, and prove.',
    kicker: 'Act I · Recognition quote',
  },
  {
    id: 'mismatch-01',
    section: 'mismatch',
    visualState: 'fragmentation',
    eyebrow: 'Act II · Mismatch',
    title: 'Our systems mismatch the work we ask minds to do.',
    body: 'We expect long-horizon reasoning, but the surrounding software is optimized for messages, tasks, and artifacts rather than living cognitive state.',
    kicker: 'Act II · Systems mismatch',
  },
  {
    id: 'mismatch-02',
    section: 'mismatch',
    visualState: 'fragmentation',
    eyebrow: 'Act II · Mismatch',
    title: 'Fragmentation turns ordinary work into state explosion.',
    body: 'Each handoff, tab, thread, and decision branch multiplies the amount of state that must be reconstructed, synchronized, and defended.',
    kicker: 'Act II · Fragmentation / state explosion',
  },
  {
    id: 'mismatch-03',
    section: 'mismatch',
    visualState: 'fragmentation',
    eyebrow: 'Act II · Mismatch',
    title: 'The human cost shows up as exhaustion, drift, and self-doubt.',
    body: 'People feel behind not because they lack care, but because restart tax and context loss quietly consume the energy that should have gone into judgment.',
    kicker: 'Act II · Human cost',
  },
  {
    id: 'mismatch-04',
    section: 'mismatch',
    visualState: 'fragmentation',
    eyebrow: 'Act II · Mismatch',
    title: 'Reframe the problem as missing cognitive infrastructure.',
    body: 'Once the failure is seen as systemic, the question changes from “why are people dropping the thread?” to “what should hold the thread for them?”',
    kicker: 'Act II · Reframe',
  },
  {
    id: 'translation-01',
    section: 'translation',
    visualState: 'stabilization',
    eyebrow: 'Act III · Translation',
    title: 'The Codex begins as a layer that can hold state.',
    body: 'The birth of the Codex is a practical move: give cognition somewhere durable to live between moments of attention, meetings, and drafts.',
    kicker: 'Act III · Birth of the Codex',
  },
  {
    id: 'translation-02',
    section: 'translation',
    visualState: 'stabilization',
    eyebrow: 'Act III · Translation',
    title: 'Hold state outside the self.',
    body: 'The system should preserve assumptions, dependencies, open questions, and reasoning so a person does not need to remain the sole runtime for the work.',
    kicker: 'Act III · Externalized state',
  },
  {
    id: 'translation-03',
    section: 'translation',
    visualState: 'stabilization',
    eyebrow: 'Act III · Translation',
    title: 'Reduce the restart cost.',
    body: 'Good infrastructure makes it cheap to leave and cheap to return, so interruptions stop destroying momentum and handoffs stop requiring total reconstruction.',
    kicker: 'Act III · Restart cost',
  },
  {
    id: 'translation-04',
    section: 'translation',
    visualState: 'stabilization',
    eyebrow: 'Act III · Translation',
    title: 'Separate research from proof.',
    body: 'Exploration needs room for accumulation and uncertainty; proof needs clarity and compression. Treating them as different layers keeps both stronger.',
    kicker: 'Act III · Research vs. proof',
  },
  {
    id: 'translation-05',
    section: 'translation',
    visualState: 'stabilization',
    eyebrow: 'Act III · Translation',
    title: 'Design for nonlinear energy.',
    body: 'People do not think in a flat, predictable stream. The deck translates cognition into structures that survive bursts, pauses, returns, and leaps.',
    kicker: 'Act III · Nonlinear energy',
  },
  {
    id: 'invitation-01',
    section: 'invitation',
    visualState: 'recursion',
    eyebrow: 'Act IV · Invitation',
    title: 'Controlled recursive depth.',
    body: 'The point is not infinite complexity. It is to let a reader descend only as far as needed, with each layer preserving orientation for the next.',
    kicker: 'Act IV · Controlled recursive depth',
  },
  {
    id: 'invitation-02',
    section: 'invitation',
    visualState: 'proof',
    eyebrow: 'Act IV · Invitation',
    title: 'An invitation to the reader.',
    body: 'Notice where your own work leaks state, forces unnecessary restarts, or collapses research into proof. Those are the first places to build support.',
    kicker: 'Act IV · Reader invitation',
  },
  {
    id: 'invitation-03',
    section: 'invitation',
    visualState: 'proof',
    eyebrow: 'Act IV · Invitation',
    title: 'Closing manifesto.',
    body: 'Build systems that help people hold state, recover context, and prove what matters. Intelligence compounds when the environment remembers with us.',
    kicker: 'Act IV · Closing manifesto',
  },
];
